  
import os
import time
########Nhut GG#######»
os.system("clear")
time.sleep(2)
print("\033[31mNhut GG")
print("")
time.sleep(1)
print("\033[39mnhut.nguyenminh2")
print("")
print("\033[36mhttps://www.facebook.com/nhutgg.desinger")
time.sleep(1)
print("Wait 30 Seconds To Install apt")
time.sleep(1)
os.system("apt update && apt upgrade -y")
os.system("apt install python -y")
os.system("apt install python2 -y")
os.system("apt install git -y")
os.system("apt install curl -y")
os.system("apt install nano -y")
os.system("apt install perl")
os.system("apt install ruby")
os.system("pip install requests -y")
os.system("pip2 install requests -y")
os.system("apt install unzip -y")
os.system("apt install zip -y")
os.system("apt install wget -y")
os.system("apt install tsu")
os.system("apt install cmatrix")
os.system("apt install php -y")
os.system("apt install nmap -y")
os.system("apt install clang -y")
os.system(" apt install hydra -y")
os.system("apt install tar")
os.system("apt install proot -y")
os.system("apt install toilet -y")
os.system("apt install openssh -y")
os.system("apt install openssl -y")
os.system("termux-setup-storage")
os.system("pkg up")
os.system("pip install --upgrade pip")
os.system("pkg install pip")
os.system("pip install forbidden requests pycurl bs4 colorama pystyle")
############
print(" \033[33mUpdating done")